#!/usr/bin/env python3

import re
import argparse
from pathlib import Path

def parse_requirements(requirements_file):
    """Parse requirements.txt file and return a list of packages."""
    packages = []
    with open(requirements_file, 'r') as f:
        for line in f:
            line = line.strip()
            # Skip comments and empty lines
            if line.startswith('#') or not line:
                continue
            # Extract package name (remove version constraints and comments)
            package = re.split(r'[<>=#]', line)[0].strip()
            if package:
                packages.append(package)
    return packages

def generate_apptainer_definition(packages, output_file='Apptainer.def'):
    """Generate an Apptainer definition file."""
    definition = f"""Bootstrap: docker
From: python:3.10-slim

%labels
    Author "Generated by generate_apptainer.py"
    Version "1.0"

%post
    # Install system dependencies
    apt-get update && apt-get install -y \\
        build-essential \\
        && rm -rf /var/lib/apt/lists/*

    # Install Python packages
    pip install --no-cache-dir \\
        {' \\\n        '.join(packages)}

%environment
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

%runscript
    exec python "$@"
"""
    with open(output_file, 'w') as f:
        f.write(definition)
    print(f"Generated {output_file}")

def main():
    parser = argparse.ArgumentParser(description='Generate Apptainer definition file from requirements.txt')
    parser.add_argument('--output', '-o', default='Apptainer.def', help='Output file path')
    args = parser.parse_args()
    
    # Get the directory of the current script
    script_dir = Path(__file__).parent
    requirements_file = script_dir / 'requirements.txt'
    
    if not requirements_file.exists():
        print(f"Error: {requirements_file} not found!")
        return
    
    packages = parse_requirements(requirements_file)
    generate_apptainer_definition(packages, args.output)

if __name__ == '__main__':
    main() 